### ISSUE TITLE
Not working on PHP7 because PHP7 uses `mysqli_` rather than `mysql_`

### ISSUE THREAD

**Issue by jinyu121** [billchenchina/UOJ-Edited#6]
I do not want to run it in docker.....

Env: Debian9 + Apache + __PHP7.0__

Error: `Call to undefined function mysql_xxxxxxxx`

Solution: change __ALL__ `mysql_` to `mysqli_` ,and add the first parameter `$link`

Another solution: Use the `DB` class you have wrote !!!

**Comment by billchenchina** [comment]
@jinyu121 

Well, you're right. This project is based on [UOJ](https://github.com/vfleaking/uoj), which doesn't support PHP7. And its code is so bad ≥﹏≤ .

If you want to deploy UOJ on your server, I strongly recommend you run it in docker, which is easy to deploy and easy to maintain. And due to a serious bug, you can't use `Java7` and `Java8` now.(Fixed in another repo)

I will update the wiki soon to tell you how to deploy. But I won't change all `mysql_` to `mysqli_` due to the default supported OS is ubuntu14. If you'd like to update all `mysql()` to `DB` class, pull requests are welcomed!

**Comment by jinyu121** [comment]
I do not want to __develop__ on docker... Frankly, no develop tutorial at all... 

PR is coming...
